### ISSUE TITLE
[Feature]:Will it be updated?

### ISSUE THREAD

**Issue by yuboabc** [rvost/PboObscure#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

FPackerEx Will there be better confusion? The class name method name variable name can be confused, making it much more difficult for other crackers to read.

**Comment by rvost** [comment]
The short answer is yes. But in the current situation I cannot give any time estimates. 

Source code obfuscation is a planned feature, but it's not easy to implement correctly, so it's unlikely to be included in the *next* update.

**Comment by yuboabc** [comment]
Okay, thanks

**Comment by FlipperPlz** [comment]
https://github.com/FlipperPlz/EnforceParser/tree/master/EnforceParser.Core

> The short answer is yes. But in the current situation I cannot give any time estimates.
> 
> Source code obfuscation is a planned feature, but it's not easy to implement correctly, so it's unlikely to be included in the _next_ update.

Feel free to use or alter any of my parser libraries, if they're under a license that you dont agree with consider it voided for you. <3

**Comment by rvost** [comment]
Sorry for the very late response. I really appreciate your great work on the parsers.

I considered using `EnforceParser` rather than reinventing the wheel, but I generally avoid messing with viral licences (I thought it was GPL-licneced, IIRC most of your libraries are GPLed). Given your comment about licensing and the fact that `EnforceParser` is actually MIT I'm happy to try it for script minifiaction & obfuscation.
